routes/web.php
<?php

$controller = "LopController";
Route::group(["prefix" => "lop","as" => "lop."],function() use ($controller){
	Route::get("","$controller@view_all")->name("view_all");
	Route::get("view_insert","$controller@view_insert")->name("view_insert");
	Route::post("process_insert","$controller@process_insert")->name("process_insert");
	Route::get("view_update/{ma}","$controller@view_update")->name("view_update");
	Route::post("process_update/{ma}","$controller@process_update")->name("process_update");
	Route::get("delete/{ma}","$controller@delete")->name("delete");
	
	Route::get("view_array_sinh_vien_by_lop/{ma}","$controller@view_array_sinh_vien_by_lop")->name("view_array_sinh_vien_by_lop");
});

$controller = "SinhVienController";
Route::group(["prefix" => "sinh_vien","as" => "sinh_vien."],function() use ($controller){
	Route::get("","$controller@view_all")->name("view_all");
	Route::get("view_insert","$controller@view_insert")->name("view_insert");
	Route::post("process_insert","$controller@process_insert")->name("process_insert");
	Route::get("view_update/{ma}","$controller@view_update")->name("view_update");
	Route::post("process_update/{ma}","$controller@process_update")->name("process_update");
	Route::get("delete/{ma}","$controller@delete")->name("delete");
});

app/Models/Lop.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Lop extends Model
{
    protected $table = 'lop';
    public $timestamps = false;
    protected $fillable = ['ten'];
    protected $primaryKey = 'ma';
    public function array_sinh_vien()
    {
        return $this->hasMany('App\Models\SinhVien','ma_lop','ma');
    }
}

app/Models/SinhVien.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class SinhVien extends Model
{
    protected $table = 'sinh_vien';
    public $timestamps = false;
    protected $fillable = [
    	'ho',
    	'ten',
    	'ngay_sinh',
    	'gioi_tinh',
    	'ma_lop',
    ];
    protected $primaryKey = 'ma';
    public function lop()
    {
        return $this->belongsTo('App\Models\Lop','ma_lop');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class Controller
{
	
}

app/Http/Controllers/LopController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Lop;

class LopController extends Controller
{
    public function view_all()
    {
    	$array_lop = Lop::all();

    	return view("lop.view_all",[
    		'array_lop' => $array_lop
    	]);
    }
    public function view_insert()
    {
    	return view("lop.view_insert");
    }
    public function process_insert(Request $rq)
    {
    	// $lop = new Lop();
    	// $lop->ten = $rq->ten;
    	// $lop->save();

    	Lop::create($rq->all());

    	return redirect()->route('lop.view_all');
    }
    public function view_update($ma)
    {
    	// $lop = Lop::where('ma','=',$ma)->first();

    	$lop = Lop::find($ma);

    	return view("lop.view_update",[
    		'lop' => $lop
    	]);
    }
    public function process_update($ma, Request $rq)
    {
    	// $lop = Lop::find($ma);
    	// $lop->ten = $rq->ten;
    	// $lop->save();

    	// Lop::find($ma)->update([
    	// 	'ten' => $rq->ten
    	// ]);

    	Lop::find($ma)->update($rq->all());
    }
    public function delete($ma)
    {
    	// $lop = Lop::find($ma);
    	// $lop->delete();

    	Lop::find($ma)->delete();
    }
    public function view_array_sinh_vien_by_lop($ma)
    {
        $array_sinh_vien = Lop::find($ma)->array_sinh_vien;
        return $array_sinh_vien;
    }

}

app/Http/Controllers/SinhVienController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Lop;
use App\Models\SinhVien;

class SinhVienController extends Controller
{
    protected $table = 'sinh_vien';
    public function view_all()
    {
    	$array_sinh_vien = SinhVien::with('lop')->get();

    	return view("$this->table.view_all",[
    		"array_sinh_vien" => $array_sinh_vien
    	]);
    }
    public function view_insert()
    {
        $array_lop = Lop::get();
    	return view("$this->table.view_insert",[
            'array_lop' => $array_lop
        ]);
    }
    public function process_insert(Request $rq)
    {
    	SinhVien::create($rq->all());

    	return redirect()->route("$this->table.view_all");
    }
    public function view_update($ma)
    {
    	$sinh_vien = SinhVien::find($ma);
        $array_lop = Lop::get();

    	return view("$this->table.view_update",[
    		"sinh_vien" => $sinh_vien,
            "array_lop" => $array_lop,
    	]);
    }
    public function process_update($ma, Request $rq)
    {
    	SinhVien::find($ma)->update($rq->all());
    }
    public function delete($ma)
    {
    	SinhVien::find($ma)->delete();
    }

}

resources/views/lop/view_all.blade.php
<a href="{{ route('lop.view_insert') }}">
	Thêm
</a>
<table border="1" width="100%">
	<tr>
		<th>Mã</th>
		<th>Tên</th>
		<th>Xem sinh viên lớp này</th>
		<th>Sửa</th>
		<th>Xoá</th>
	</tr>
	@foreach ($array_lop as $lop)
		<tr>
			<td>
				{{ $lop->ma }}
			</td>
			<td>
				{{ $lop->ten }}
			</td>
			<td>
				<a href="{{ route('lop.view_array_sinh_vien_by_lop',['ma' => $lop->ma]) }}">
					Xem sinh viên
				</a>
			</td>
			<td>
				<a href="{{ route('lop.view_update',['ma' => $lop->ma]) }}">
					Sửa
				</a>
			</td>
			<td>
				<a href="{{ route('lop.delete',['ma' => $lop->ma]) }}">
					Xoá
				</a>
			</td>
		</tr>
	@endforeach
</table>

resources/views/lop/view_insert.blade.php
<form action="{{ route('lop.process_insert') }}" method="post">
	{{ csrf_field() }}
	Tên
	<input type="text" name="ten">
	<br>
	<button>Thêm</button>
</form>

resources/views/lop/view_update.blade.php
<form action="{{ route('lop.process_update',['ma' => $lop->ma]) }}" method="post">
	{{ csrf_field() }}
	Tên
	<input type="text" name="ten" value="{{ $lop->ten }}">
	<br>
	<button>Sửa</button>
</form>

resources/views/sinh_vien/view_all.blade.php
<a href="{{ route('sinh_vien.view_insert') }}">
	Thêm
</a>
<table border="1" width="100%">
	<tr>
		<th>Mã</th>
		<th>Họ</th>
		<th>Tên</th>
		<th>Ngày sinh</th>
		<th>Giới tính</th>
		<th>Tên lớp</th>
		<th>Sửa</th>
		<th>Xoá</th>
	</tr>
	@foreach ($array_sinh_vien as $sinh_vien)
		<tr>
			<td>
				{{ $sinh_vien->ma }}
			</td>
			<td>
				{{ $sinh_vien->ho }}
			</td>
			<td>
				{{ $sinh_vien->ten }}
			</td>
			<td>
				{{ $sinh_vien->ngay_sinh }}
			</td>
			<td>
				{{ $sinh_vien->gioi_tinh }}
			</td>
			<td>
				{{ $sinh_vien->lop->ten }}
			</td>
			<td>
				<a href="{{ route('sinh_vien.view_update',['ma' => $sinh_vien->ma]) }}">
					Sửa
				</a>
			</td>
			<td>
				<a href="{{ route('sinh_vien.delete',['ma' => $sinh_vien->ma]) }}">
					Xoá
				</a>
			</td>
		</tr>
	@endforeach
</table>

resources/views/sinh_vien/view_insert.blade.php
<form action="{{ route('sinh_vien.process_insert') }}" method="post">
	{{ csrf_field() }}
	Họ
	<input type="text" name="ho">
	<br>
	Tên
	<input type="text" name="ten">
	<br>
	Ngày sinh
	<input type="date" name="ngay_sinh">
	<br>
	Giới tính
	<input type="radio" name="gioi_tinh" value="1">Nữ
	<input type="radio" name="gioi_tinh" value="0">Nam
	<br>
	Lớp
	<select name="ma_lop">
		@foreach ($array_lop as $lop)
			<option value="{{ $lop->ma }}">
				{{ $lop->ten }}
			</option>
		@endforeach
	</select>
	<br>
	<button>Thêm</button>
</form>

resources/views/sinh_vien/view_update.blade.php
<form action="{{ route('sinh_vien.process_update',['ma' => $sinh_vien->ma]) }}" method="post">
	{{ csrf_field() }}
	Họ
	<input type="text" name="ho" value="{{ $sinh_vien->ho }}">
	<br>
	Tên
	<input type="text" name="ten" value="{{ $sinh_vien->ten }}">
	<br>
	Ngày sinh
	<input type="date" name="ngay_sinh" value="{{ $sinh_vien->ngay_sinh }}">
	<br>
	Giới tính
	<input type="radio" name="gioi_tinh" value="1" 
	@if ($sinh_vien->gioi_tinh==1)
		checked 
	@endif>Nữ
	<input type="radio" name="gioi_tinh" value="0" 
	@if ($sinh_vien->gioi_tinh==0)
		checked 
	@endif>Nam
	<br>
	Lớp
	<select name="ma_lop">
		@foreach ($array_lop as $lop)
			<option value="{{ $lop->ma }}"
			@if ($lop->ma == $sinh_vien->ma_lop)
				selected 
			@endif
			>
				{{ $lop->ten }}
			</option>
		@endforeach
	</select>
	<br>
	<button>Sửa</button>
</form>